name: Release Process

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run enhanced tests
        run: npm run test:enhanced
      
      - name: Run linting
        run: npm run lint
      
      - name: Run security audit
        run: npm audit --audit-level=high
        continue-on-error: true
      
      - name: Bump version
        id: version
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Update CHANGELOG
        run: |
          echo "## [Unreleased]" > CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "## [${{ steps.version.outputs.version }}] - $(date +%Y-%m-%d)" >> CHANGELOG.tmp
          tail -n +2 CHANGELOG.md >> CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
      
      - name: Commit version bump
        run: |
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "chore: release v${{ steps.version.outputs.version }}"
      
      - name: Create and push tag
        run: |
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
          git push origin main --follow-tags
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          # Extract changelog section for this version
          CHANGELOG_SECTION=$(awk "/^## \[$VERSION\]/, /^## \[/ { if (!/^## \[/ || /^## \[$VERSION\]/) print }" CHANGELOG.md | head -n -1)
          # Remove the version header line
          CHANGELOG_BODY=$(echo "$CHANGELOG_SECTION" | tail -n +2)
          # Set output using heredoc to handle multiline
          {
            echo 'body<<EOF'
            echo "## What's Changed"
            echo ""
            if [ -n "$CHANGELOG_BODY" ]; then
              echo "$CHANGELOG_BODY"
            else
              echo "See [CHANGELOG.md](https://github.com/robwhite4/claude-memory/blob/main/CHANGELOG.md) for details."
            fi
            echo ""
            echo "**Full Changelog**: https://github.com/robwhite4/claude-memory/compare/v1.2.0...v$VERSION"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
      
      - name: Build release artifacts
        run: |
          mkdir -p dist
          
          # Create distributable package
          npm pack --pack-destination=dist
          
          # Generate installation guide
          cat > dist/INSTALL.md << 'EOF'
          # Claude Memory v${{ steps.version.outputs.version }} - Installation Guide
          
          ## Quick Install
          ```bash
          npm install -g claude-memory@${{ steps.version.outputs.version }}
          ```
          
          ## Verify Installation
          ```bash
          claude-memory --version
          cmem --help
          ```
          
          ## First Run
          ```bash
          # Initialize in your project
          cd your-project
          claude-memory session start "Getting Started"
          ```
          
          ## Documentation
          - [Full README](https://github.com/robwhite4/claude-memory#readme)
          - [Contributing Guide](https://github.com/robwhite4/claude-memory/blob/main/CONTRIBUTING.md)
          - [Changelog](https://github.com/robwhite4/claude-memory/blob/main/CHANGELOG.md)
          EOF
          
          # Create checksums
          cd dist
          sha256sum * > checksums.txt
          ls -la
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/claude-memory-${{ steps.version.outputs.version }}.tgz
            dist/INSTALL.md
            dist/checksums.txt